# Generated by Django 4.1.7 on 2024-01-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colour', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50, unique=True)),
                ('Address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.PositiveIntegerField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense', models.CharField(max_length=50)),
                ('Amount', models.PositiveIntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otherincome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_cone', models.PositiveIntegerField(default=0)),
                ('Bag', models.PositiveIntegerField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staffprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_number', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tp', models.PositiveIntegerField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inward', models.FloatField(default=0)),
                ('Outward', models.FloatField(default=0)),
                ('Bag', models.FloatField(default=0)),
                ('Amount', models.FloatField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colour')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('Count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.count')),
                ('Tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tp')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inward', models.FloatField(default=0)),
                ('Outward', models.FloatField(default=0)),
                ('Tfo_shift', models.FloatField(default=0)),
                ('Cheese_bag', models.PositiveIntegerField(default=0)),
                ('Waste', models.PositiveIntegerField(default=0)),
                ('Doubled_bag', models.PositiveIntegerField(default=0)),
                ('Total_salary', models.FloatField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colour')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('Count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.count')),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile')),
                ('Stocks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.stocks')),
                ('Tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tp')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tfo_price', models.PositiveBigIntegerField(default=1)),
                ('Cheese_price', models.PositiveBigIntegerField(default=1)),
                ('Doubled_price', models.PositiveBigIntegerField(default=1)),
                ('Per_bag', models.FloatField(default=1)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('Count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.count')),
                ('Tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tp')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advance', models.PositiveIntegerField(default=0)),
                ('Bonus', models.PositiveIntegerField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile')),
            ],
        ),
    ]
